import {PlanetOsmRow} from "./_planet_osm";

export type PlanetOsmPointRow = PlanetOsmRow & {
    access: string | null
    "addr:housename": string | null
    "addr:housenumber": string | null
    "addr:interpolation": string | null
    admin_level: string | null
    aerialway: string | null
    aeroway: string | null
    amenity: string | null
    area: string | null
    barrier: string | null
    bicycle: string | null
    brand: string | null
    bridge: string | null
    boundary: string | null
    building: string | null
    capital: string | null
    construction: string | null
    covered: string | null
    culvert: string | null
    cutting: string | null
    denomination: string | null
    disused: string | null
    ele: string | null
    embankment: string | null
    foot: string | null
    "generator:source": string | null
    harbour: string | null
    highway: string | null
    historic: string | null
    horse: string | null
    intermittent: string | null
    junction: string | null
    landuse: string | null
    layer: string | null
    leisure: string | null
    lock: string | null
    man_made: string | null
    military: string | null
    motorcar: string | null
    name: string | null
    natural: string | null
    office: string | null
    oneway: string | null
    operator: string | null
    place: string | null
    population: string | null
    power: string | null
    power_source: string | null
    public_transport: string | null
    railway: string | null
    ref: string | null
    religion: string | null
    route: string | null
    service: string | null
    shop: string | null
    sport: string | null
    surface: string | null
    toll: string | null
    tourism: string | null
    "tower:type": string | null
    tunnel: string | null
    water: string | null
    waterway: string | null
    wetland: string | null
    width: string | null
    wood: string | null
}